import { lazy } from 'react';
import { MonitorPlay } from 'lucide-react';
import type { ModuleManifest } from '../_types';

export const manifest: ModuleManifest = {
  id: 'led-display',
  name: 'LED Display Management',
  description: 'Manage LED display projects for construction and infrastructure - from planning and procurement to installation and maintenance',
  version: '1.0.0',
  icon: MonitorPlay,
  category: 'planning',
  defaultEnabled: false,
  depends: ['projects'],
  routes: [
    {
      path: '/led-display',
      title: 'LED Displays',
      component: lazy(() => import('./LEDDisplayModule')),
    },
    {
      path: '/led-display/:projectId',
      title: 'LED Project Details',
      component: lazy(() => import('./LEDDisplayModule')),
    },
  ],
  navItems: [
    {
      labelKey: 'nav.led_display',
      to: '/led-display',
      icon: MonitorPlay,
      group: 'planning',
      advancedOnly: true,
    },
  ],
  searchEntries: [
    {
      label: 'LED Display Projects',
      path: '/led-display',
      keywords: ['led', 'display', 'screen', 'signage', 'monitor', 'video_wall'],
    },
  ],
  translations: {
    en: {
      'nav.led_display': 'LED Displays',
      'led.title': 'LED Display Projects',
      'led.new_project': 'New LED Project',
      'led.display_type': 'Display Type',
      'led.indoor': 'Indoor',
      'led.outdoor': 'Outdoor',
      'led.semi_outdoor': 'Semi-Outdoor',
      'led.transparent': 'Transparent',
      'led.curtain': 'Curtain',
      'led.rental': 'Rental',
      'led.screen_size': 'Screen Size',
      'led.pixel_pitch': 'Pixel Pitch',
      'led.brightness': 'Brightness',
      'led.resolution': 'Resolution',
      'led.installation_location': 'Installation Location',
      'led.status': 'Status',
      'led.planning': 'Planning',
      'led.procurement': 'Procurement',
      'led.installation': 'Installation',
      'led.testing': 'Testing',
      'led.completed': 'Completed',
      'led.operational': 'Operational',
      'led.maintenance': 'Maintenance',
      'led.panels': 'Panels',
      'led.controllers': 'Controllers',
      'led.inventory': 'Inventory',
      'led.installations': 'Installations',
      'led.milestones': 'Milestones',
      'led.maintenance_logs': 'Maintenance Logs',
      'led.documents': 'Documents',
      'led.budget': 'Budget',
      'led.stats': 'Project Statistics',
      'led.total_panels': 'Total Panels',
      'led.installed_panels': 'Installed',
      'led.operational_panels': 'Operational',
      'led.damaged_panels': 'Damaged',
      'led.total_controllers': 'Total Controllers',
      'led.faulty_controllers': 'Faulty',
      'led.budget_total': 'Total Budget',
      'led.budget_spent': 'Spent',
      'led.budget_remaining': 'Remaining',
      'led.progress': 'Installation Progress',
      'led.upcoming_maintenance': 'Upcoming Maintenance',
      'led.no_projects': 'No LED projects found',
      'led.create_first': 'Create your first LED display project to get started',
    },
    de: {
      'nav.led_display': 'LED-Anzeigen',
      'led.title': 'LED-Anzeigeprojekte',
      'led.new_project': 'Neues LED-Projekt',
      'led.display_type': 'Anzeigetyp',
      'led.indoor': 'Innenbereich',
      'led.outdoor': 'Außenbereich',
      'led.semi_outdoor': 'Halb-Außenbereich',
      'led.transparent': 'Transparent',
      'led.curtain': 'Vorhang',
      'led.rental': 'Vermietung',
      'led.screen_size': 'Bildschirmgröße',
      'led.pixel_pitch': 'Pixelabstand',
      'led.brightness': 'Helligkeit',
      'led.resolution': 'Auflösung',
      'led.installation_location': 'Installationsort',
      'led.status': 'Status',
      'led.planning': 'Planung',
      'led.procurement': 'Beschaffung',
      'led.installation': 'Installation',
      'led.testing': 'Testen',
      'led.completed': 'Abgeschlossen',
      'led.operational': 'In Betrieb',
      'led.maintenance': 'Wartung',
      'led.panels': 'Panels',
      'led.controllers': 'Steuerungen',
      'led.inventory': 'Inventar',
      'led.installations': 'Installationen',
      'led.milestones': 'Meilensteine',
      'led.maintenance_logs': 'Wartungsprotokolle',
      'led.documents': 'Dokumente',
      'led.budget': 'Budget',
      'led.stats': 'Projektstatistiken',
      'led.total_panels': 'Gesamtpanels',
      'led.installed_panels': 'Installiert',
      'led.operational_panels': 'In Betrieb',
      'led.damaged_panels': 'Beschädigt',
      'led.total_controllers': 'Gesamtsteuerungen',
      'led.faulty_controllers': 'Fehlerhaft',
      'led.budget_total': 'Gesamtbudget',
      'led.budget_spent': 'Ausgegeben',
      'led.budget_remaining': 'Verbleibend',
      'led.progress': 'Installationsfortschritt',
      'led.upcoming_maintenance': 'Anstehende Wartung',
      'led.no_projects': 'Keine LED-Projekte gefunden',
      'led.create_first': 'Erstellen Sie Ihr erstes LED-Anzeigeprojekt',
    },
    fr: {
      'nav.led_display': 'Écrans LED',
      'led.title': 'Projets d\'affichage LED',
      'led.new_project': 'Nouveau projet LED',
      'led.display_type': 'Type d\'affichage',
      'led.indoor': 'Intérieur',
      'led.outdoor': 'Extérieur',
      'led.semi_outdoor': 'Semi-Extérieur',
      'led.transparent': 'Transparent',
      'led.curtain': 'Rideau',
      'led.rental': 'Location',
      'led.screen_size': 'Taille d\'écran',
      'led.pixel_pitch': 'Pitch de pixel',
      'led.brightness': 'Luminosité',
      'led.resolution': 'Résolution',
      'led.installation_location': 'Lieu d\'installation',
      'led.status': 'Statut',
      'led.planning': 'Planification',
      'led.procurement': 'Approvisionnement',
      'led.installation': 'Installation',
      'led.testing': 'Test',
      'led.completed': 'Terminé',
      'led.operational': 'Opérationnel',
      'led.maintenance': 'Maintenance',
      'led.panels': 'Panneaux',
      'led.controllers': 'Contrôleurs',
      'led.inventory': 'Inventaire',
      'led.installations': 'Installations',
      'led.milestones': 'Jalons',
      'led.maintenance_logs': 'Journaux de maintenance',
      'led.documents': 'Documents',
      'led.budget': 'Budget',
      'led.stats': 'Statistiques du projet',
      'led.total_panels': 'Total panneaux',
      'led.installed_panels': 'Installés',
      'led.operational_panels': 'Opérationnels',
      'led.damaged_panels': 'Endommagés',
      'led.total_controllers': 'Total contrôleurs',
      'led.faulty_controllers': 'Défectueux',
      'led.budget_total': 'Budget total',
      'led.budget_spent': 'Dépensé',
      'led.budget_remaining': 'Restant',
      'led.progress': 'Progression de l\'installation',
      'led.upcoming_maintenance': 'Maintenance à venir',
      'led.no_projects': 'Aucun projet LED trouvé',
      'led.create_first': 'Créez votre premier projet d\'affichage LED',
    },
    ru: {
      'nav.led_display': 'LED-экраны',
      'led.title': 'Проекты LED-экранов',
      'led.new_project': 'Новый LED-проект',
      'led.display_type': 'Тип экрана',
      'led.indoor': 'Внутренний',
      'led.outdoor': 'Наружный',
      'led.semi_outdoor': 'Полунаружный',
      'led.transparent': 'Прозрачный',
      'led.curtain': 'Занавес',
      'led.rental': 'Аренда',
      'led.screen_size': 'Размер экрана',
      'led.pixel_pitch': 'Шаг пикселя',
      'led.brightness': 'Яркость',
      'led.resolution': 'Разрешение',
      'led.installation_location': 'Место установки',
      'led.status': 'Статус',
      'led.planning': 'Планирование',
      'led.procurement': 'Закупка',
      'led.installation': 'Монтаж',
      'led.testing': 'Тестирование',
      'led.completed': 'Завершен',
      'led.operational': 'В эксплуатации',
      'led.maintenance': 'Обслуживание',
      'led.panels': 'Панели',
      'led.controllers': 'Контроллеры',
      'led.inventory': 'Инвентарь',
      'led.installations': 'Монтажные работы',
      'led.milestones': 'Вехи',
      'led.maintenance_logs': 'Журналы обслуживания',
      'led.documents': 'Документы',
      'led.budget': 'Бюджет',
      'led.stats': 'Статистика проекта',
      'led.total_panels': 'Всего панелей',
      'led.installed_panels': 'Установлено',
      'led.operational_panels': 'В работе',
      'led.damaged_panels': 'Повреждено',
      'led.total_controllers': 'Всего контроллеров',
      'led.faulty_controllers': 'Неисправно',
      'led.budget_total': 'Общий бюджет',
      'led.budget_spent': 'Потрачено',
      'led.budget_remaining': 'Остаток',
      'led.progress': 'Прогресс монтажа',
      'led.upcoming_maintenance': 'Предстоящее обслуживание',
      'led.no_projects': 'LED-проекты не найдены',
      'led.create_first': 'Создайте свой первый проект LED-экрана',
    },
  },
};