// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
// Generated by backend/tests/fixtures/trainer/generate_api_fixtures.py from the
// backend Pydantic schemas. Do not edit by hand: change the generator and rerun it.
import type { AttemptResult } from '../types';

export const attemptFailFixture: AttemptResult = {
  "attempt_id": "3f0b8d6e-1c2a-4b5d-9e8f-7a6b5c4d3e21",
  "client_attempt_id": "0d9c8b7a-6f5e-4d3c-8b2a-1f0e9d8c7b61",
  "task_id": "t2-markups",
  "verdict": "fail",
  "graded_items": 5,
  "passed_items": 3,
  "fields": [
    {
      "key": "overheads_amount",
      "source": "panel",
      "verdict": "ok",
      "observed": "2433.12",
      "diagnosis": null,
      "feedback": null
    },
    {
      "key": "grand_total",
      "source": "erp",
      "verdict": "wrong",
      "observed": "34489.48",
      "diagnosis": {
        "id": "t2-profit-compounded",
        "kind": "error",
        "message": "Profit was charged on the overheads as well.",
        "related": [
          {
            "name": "fx_profit_amount",
            "value": "1520.70",
            "kind": "money",
            "label": "Profit amount"
          }
        ]
      },
      "feedback": null
    },
    {
      "key": "profit_rate",
      "source": "erp",
      "verdict": "ok",
      "observed": "5.00",
      "diagnosis": null,
      "feedback": null
    },
    {
      "key": "t2-trace",
      "source": "panel",
      "verdict": "ok",
      "observed": "0",
      "diagnosis": null,
      "feedback": "Yes: 30414.00 x 5% = 1520.70."
    },
    {
      "key": "t2-explain",
      "source": "panel",
      "verdict": "wrong",
      "observed": "1",
      "diagnosis": null,
      "feedback": "Rounding moves a few pence, not 121.66."
    }
  ],
  "task_status": "needs_revision",
  "rings": {
    "numbers": false,
    "trace": true,
    "explain": false
  },
  "progress": {
    "done": 1,
    "total": 5,
    "rings": {
      "numbers": {
        "done": 1,
        "total": 5
      },
      "trace": {
        "done": 2,
        "total": 5
      },
      "explain": {
        "done": 1,
        "total": 5
      }
    }
  },
  "unlocked": [],
  "regressed": false,
  "revealed_hint": "Both markups apply to direct cost.",
  "checked_at": "2026-10-05T10:40:00Z"
};
