// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
// Generated by backend/tests/fixtures/trainer/generate_api_fixtures.py from the
// backend Pydantic schemas. Do not edit by hand: change the generator and rerun it.
import type { ReadbackResponse } from '../types';

export const readbackFixture: ReadbackResponse = {
  "task_id": "t2-markups",
  "items": [
    {
      "id": "rb0",
      "state": "mismatch",
      "app_value": "34489.48",
      "kind": "money",
      "reason_key": null
    },
    {
      "id": "rb1",
      "state": "match",
      "app_value": "5.00",
      "kind": "percent",
      "reason_key": null
    }
  ],
  "read_at": "2026-10-05T10:40:00Z"
};
