// DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
// Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
// Generated by backend/tests/fixtures/trainer/generate_api_fixtures.py from the
// backend Pydantic schemas. Do not edit by hand: change the generator and rerun it.
import type { TaskView } from '../types';

export const taskFixture: TaskView = {
  "id": "t2-markups",
  "n": 2,
  "title": "Add overheads and profit",
  "module": "boq",
  "status": "needs_revision",
  "brief": "Add the overheads and profit the firm agreed for this job, both on direct cost.",
  "given": [
    {
      "name": "Overheads rate",
      "value": "8",
      "kind": "percent"
    },
    {
      "name": "Profit rate",
      "value": "5",
      "kind": "percent"
    }
  ],
  "steps": [
    "Open the markups panel of the main bill.",
    "Add overheads at 8 per cent on direct cost.",
    "Add profit at 5 per cent on direct cost.",
    "Type the overheads amount; the checker reads the grand total from the bill."
  ],
  "hints": [
    "Both markups apply to direct cost."
  ],
  "hints_total": 2,
  "panel_notes": [],
  "has_date_steps": false,
  "checks": [
    {
      "id": "t2-numbers",
      "kind": "numbers",
      "prompt": "Type the overheads amount.",
      "fields": [
        {
          "key": "overheads_amount",
          "label": "Overheads",
          "kind": "money",
          "currency": "GBP"
        }
      ]
    },
    {
      "id": "t2-trace",
      "kind": "trace",
      "prompt": "What is profit calculated on?",
      "options": [
        {
          "index": 0,
          "text": "Direct cost only."
        },
        {
          "index": 1,
          "text": "Direct cost plus overheads."
        },
        {
          "index": 2,
          "text": "The grand total."
        }
      ]
    },
    {
      "id": "t2-explain",
      "kind": "explain",
      "prompt": "Why does compounding profit change the total?",
      "options": [
        {
          "index": 0,
          "text": "Profit would also be charged on the overheads."
        },
        {
          "index": 1,
          "text": "The ERP rounds each markup."
        },
        {
          "index": 2,
          "text": "Overheads are counted twice."
        }
      ]
    }
  ],
  "readback": [
    {
      "id": "rb0",
      "what": "Grand total of the main bill",
      "kind": "money"
    },
    {
      "id": "rb1",
      "what": "Percentage of the profit markup",
      "kind": "percent"
    }
  ],
  "answers": [
    {
      "name": "overheads_amount",
      "kind": "number",
      "value_text": "2433.12",
      "option_index": null
    },
    {
      "name": "t2-trace",
      "kind": "option",
      "value_text": null,
      "option_index": 0
    },
    {
      "name": "t2-explain",
      "kind": "option",
      "value_text": null,
      "option_index": 1
    }
  ],
  "answers_revision": 3,
  "last_attempt": {
    "attempt_id": "3f0b8d6e-1c2a-4b5d-9e8f-7a6b5c4d3e21",
    "client_attempt_id": "0d9c8b7a-6f5e-4d3c-8b2a-1f0e9d8c7b61",
    "task_id": "t2-markups",
    "verdict": "fail",
    "graded_items": 5,
    "passed_items": 3,
    "fields": [
      {
        "key": "overheads_amount",
        "source": "panel",
        "verdict": "ok",
        "observed": "2433.12",
        "diagnosis": null,
        "feedback": null
      },
      {
        "key": "grand_total",
        "source": "erp",
        "verdict": "wrong",
        "observed": "34489.48",
        "diagnosis": {
          "id": "t2-profit-compounded",
          "kind": "error",
          "message": "Profit was charged on the overheads as well.",
          "related": [
            {
              "name": "fx_profit_amount",
              "value": "1520.70",
              "kind": "money",
              "label": "Profit amount"
            }
          ]
        },
        "feedback": null
      },
      {
        "key": "profit_rate",
        "source": "erp",
        "verdict": "ok",
        "observed": "5.00",
        "diagnosis": null,
        "feedback": null
      },
      {
        "key": "t2-trace",
        "source": "panel",
        "verdict": "ok",
        "observed": "0",
        "diagnosis": null,
        "feedback": "Yes: 30414.00 x 5% = 1520.70."
      },
      {
        "key": "t2-explain",
        "source": "panel",
        "verdict": "wrong",
        "observed": "1",
        "diagnosis": null,
        "feedback": "Rounding moves a few pence, not 121.66."
      }
    ],
    "task_status": "needs_revision",
    "rings": {
      "numbers": false,
      "trace": true,
      "explain": false
    },
    "progress": {
      "done": 1,
      "total": 5,
      "rings": {
        "numbers": {
          "done": 1,
          "total": 5
        },
        "trace": {
          "done": 2,
          "total": 5
        },
        "explain": {
          "done": 1,
          "total": 5
        }
      }
    },
    "unlocked": [],
    "regressed": false,
    "revealed_hint": "Both markups apply to direct cost.",
    "checked_at": "2026-10-05T10:40:00Z"
  }
};
